### ISSUE TITLE
[v3.12.3+fabric-1.21.1] Crashes with Screenshot Viewer

### ISSUE THREAD

**Issue by notrohit1702** [TheCSMods/mc-tcdcommons#16] opened 2024-11-02 09:52 UTC
### What happened?

When the game is launched with Fabric API, TCDCommons API and Screenshot Viewer installed, a crash happens.

### Steps to reproduce

1. Install Fabric Loader 0.16.9 on Minecraft 1.21.1
2. Download [Fabric API 0.107.0](https://modrinth.com/mod/fabric-api/version/0.107.0+1.21.1), [Screenshot Viewer 1.3.3](https://modrinth.com/mod/screenshot-viewer/version/1.21-fabric-1) and [TCDCommons API 3.12.3](https://modrinth.com/mod/tcdcommons/version/3.12.3+fabric-1.21)
3. Launch the game
4. Once the game window is opened, it crashes before anything gets a chance to load.

### Relevant log output or crash report

```shell
latest.log: https://mclo.gs/AUma1dz
Crash log: https://mclo.gs/jCJxMjY
```

### Other installed mods

1. [Fabric API 0.107.0](https://modrinth.com/mod/fabric-api/version/0.107.0+1.21.1)
2. [Screenshot Viewer 1.3.3](https://modrinth.com/mod/screenshot-viewer/version/1.21-fabric-1)
3. [TCDCommons API 3.12.3](https://modrinth.com/mod/tcdcommons/version/3.12.3+fabric-1.21)

### Code of Conduct

- [X] I agree that if the issue is regarding a crash, I gave the logs and the crash report.
- [X] I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.

**Comment by notrohit1702** [comment] 2024-11-02 09:54
This has also been reported to their GitHub: https://github.com/LGatodu47/ScreenshotViewer/issues/49

**Comment by TheCSDev** [comment] 2024-11-02 11:32
After looking into the crash report, it appears both mods are attempting to modify the same line of Minecraft's code, causing an incompatibility.  
Given my use-case is not "essential" to the behavior of my mods, I will try fixing it on my end by marking my Mixin with `require=0` (aka making it not required). Hopefully that fixes it. Thnaks for reporting this.

**Comment by TheCSDev** [comment] 2024-11-02 11:42
After looking into my mod's source code, it already uses `require=0` on my end. This means that on my end, the Mixin is marked as "not required". Strage how the conflict still happens regardless, when Spongepowered Mixin handler could just ignore mine since it's marked as "not required". Perhaps in older TCDC versions it isn't marked as required? I will have to look further into this.

Interestingly, it is ***not*** marked as required on the other mod's end, likely because they do depend on it.

So I suppose this is no fault of either mod, it's just a simple conflict in how Mixin-s are handled by the game, and how both of us modify the same line of code.

- My line: https://github.com/TheCSMods/mc-tcdcommons/blob/111c773f3c3d34c53873e409157e26270a839ca2/tcdcommons-3-fabric-1.21.3/src/main/java/io/github/thecsdev/tcdcommons/client/mixin/events/MixinNativeImage.java#L20
- Their line: https://github.com/LGatodu47/ScreenshotViewer/blob/5cd23ac63b952a8087aa34cd76a74c0c9546392c/src/main/java/io/github/lgatodu47/screenshot_viewer/mixin/NativeImageMixin.java#L12

**Edit:**
I am just now relizing my Mixin uses a higher "priority" value, despite being marked as "not required". Perhaps this is the cause. I will reset this "priority" value and hope for the best.

**Comment by TheCSDev** [comment] 2024-11-02 13:20
All done. I managed to fix the issue on my end, as it was indeed originating from my end.  
Thanks again for reporting this, and have a great day!

**Closed as completed by TheCSDev** 2024-11-02 13:20 UTC
Labels: Bug, Resolved
